<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MSI" failures="1" tests="1" name="Linux-Chrome" time="42.683" errors="0" timestamp="2025-06-14T01:18:45 IST">
  <testcase classname="testCases.TC_0001_UserCreationHappyFlow" name="userCreationHappyFlow" time="14.414">
    <failure type="java.lang.AssertionError" message="Test failed due to exception">
      <![CDATA[java.lang.AssertionError: Test failed due to exception
at testCases.TC_0001_UserCreationHappyFlow.userCreationHappyFlow(TC_0001_UserCreationHappyFlow.java:107)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- userCreationHappyFlow -->
</testsuite> <!-- Linux-Chrome -->
